CREATE TABLE Band(
  Band_ID INT PRIMARY KEY AUTO_INCREMENT,
  Name VARCHAR(30),
  Level VARCHAR(30),
  Training VARCHAR(150),
  Competencies VARCHAR(150),
  Responsibilities VARCHAR(150)
);
CREATE TABLE Capabilities(
  Cap_ID INT PRIMARY KEY AUTO_INCREMENT,
  Name VARCHAR(50),
  Job_Family VARCHAR(50)
);
CREATE TABLE JobRoles(
  Role_ID INT PRIMARY KEY AUTO_INCREMENT,
  Name VARCHAR (70),
  Spec_Sum VARCHAR(255),
  Cap_ID INT NOT NULL,
  Band_ID INT NOT NULL,
  CONSTRAINT Cap_ID FOREIGN KEY(Cap_ID) REFERENCES Capabilities(Cap_ID),
  CONSTRAINT Band_ID FOREIGN KEY(Band_ID) REFERENCES Band(Band_ID)
);
